services:
  mongo:
    image: mongo:7
    container_name: paradigm-mongo
    ports: ["27017:27017"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: paradigm-redis
    ports: ["6379:6379"]

  minio:
    image: minio/minio:latest
    container_name: paradigm-minio
    command: server /data --console-address ":9090"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin123
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio_data:/data

volumes:
  mongo_data:
  minio_data:
